project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "**/**/*.qmd"

website:
  title: "Tra Tran"
  navbar:
    left:
      - href: home/index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: projects/index.qmd
        text: Project
      - href: blog/index.qmd
        text: Blog
    right:
      - href: https://github.com/tranlevantra/tranlevantra.github.io
        icon: github

  sidebar:
    - id: fullfillmentCenter
      title: "Distribution Center Project"
      style: docked
      contents:
        - section: "Report"
          contents:
            - text: "1. Project Overview"
              file: projects/posts/fullfillmentCenter.qmd
            - text: "2. Analysis"
              file: projects/Greater Melbourne Distribution Center Landscape/analysis.qmd
        - section: "How I built this"
          contents:
            - text: "1. Warehouse Locations Leaflet Map"
              file: projects/Greater Melbourne Distribution Center Landscape/warehouseLocations.qmd
            - text: "2. Population Density Dot Plot"
              file: projects/Greater Melbourne Distribution Center Landscape/populationDensity.qmd

    - id: homeLoanScorecard
      title: "Home Loan Scorecard"
      style: docked
      contents:
        - section: "Home Loan Scorecard"
          contents:
            - text: "1. Executive Summary"
              file: projects/Home Loan Scorecard/Executive Summary.qmd
            - text: "2. Exploratory Data Analysis"
              file:  projects/Home Loan Scorecard/Exploratory Data Analysis.qmd
            - section: "3. Modeling and Scorecard Development"
              contents:
                - text: "3.1. Feature Selection"
                  file: projects/Home Loan Scorecard/Feature Selection.qmd
                - text: "3.2. Missing Values and Imputation"
                  file: projects/Home Loan Scorecard/Missing Values and Imputation.qmd
                - text: "3.3. Model Selection"
                  file: projects/Home Loan Scorecard/Model Selection.qmd
                - text: "3.4. Scorecard"
                  file: projects/Home Loan Scorecard/Scorecard.qmd
            - text: "3. Discussion"
              file: projects/Home Loan Scorecard/Discussion.qmd
            - text: "4. Conclusion"
              file: projects/Home Loan Scorecard/Conclusion.qmd
              
              

  
  page-footer: 
    center: This website is built with [Quarto](https://quarto.org/docs/websites/) and hosted on [Github Pages](https://pages.github.com)

format:
  html:
    link-external-newwindow: true
    link-external-icon: true
    theme: cosmo
    css: styles.css

editor: visual

