---
title: "Findings and Analysis"
---

::: {.callout-note collapse="true" title="Terminology alert!!!"}
### Fulfillment Center

Fulfillment centers are specialised warehouses that **store finished products** and **prepare, pack, and ship customer orders** - typically for e-commerce - either directly to consumers or to retail stores.

### Key Characteristics of Fulfillment Centers

-   *Strategic location*: Often near transport hubs and densely populated areas to ensure fast, efficient delivery to end customers.

-   *High scalability*: Designed to handle large, fluctuating volumes of small-parcel, multi-item orders shipped to geographically dispersed destinations. Advanced technology and automation are often required to maintain speed and accuracy.

### Two Main Types of Fulfillment Centers

-   **3PL (Third-Party Logistics)**:\
    Operated by logistics providers, offering warehousing and order fulfillment services to multiple companies — ideal for small e-commerce businesses without in-house logistics capabilities.

-   **In-House**:\
    Managed by the product-selling company itself, typically used by large retailers or brands with high order volumes and their own delivery team for better control over operations.
:::

## Findings

<iframe src="fig/fulfillmentCenterLandscape.html" width="100%" height="600px" style="border:none;">

</iframe>

**Note**: Information on fulfillment centers in Greater Melbourne was collected through *manual searches on Google Maps*, *company website visits*, *news articles*, and *LinkedIn posts*. The data is not exhaustive and may not represent the complete landscape of fulfillment centers in the region.

## Analysis

-   As the pandemic exposed the risks of outsourcing, **more in-house fulfillment centers are being built**. Major supermarket chains such as Coles, Woolworths, and MetCash-IGA only began developing their own distribution centers after COVID-19. Coles, for instance, relied on Linfox as its 3PL provider in 2018 but is now constructing its first in-house, fully automated facility in Melbourne. Among established names, only Aldi had its own center as early as 2010—its market-leading position highlights the benefits of taking full control over the supply chain.

-   Despite the e-commerce boom, **the 3PL market remains heavily dominated by Amazon**, which continues to expand with mega fulfillment centers.

-   **Fully automated fulfillment centers** are becoming the norm, with new warehouses built by large, well-capitalized players like Amazon and Coles. These technologies are often out of reach for smaller operators, raising market barriers for new entrants.

-   **Altona, Laverton North, and Truganina** remain key warehousing hubs, supported by prime location and ample land reserves for ongoing industrial development.
